framework:
    messenger:
        default_bus: messenger.bus.command
        # failure_transport: failed
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed
        buses:
            messenger.bus.command:
                default_middleware: false
                middleware:
                    - handle_message

            messenger.bus.query:
                default_middleware: false
                middleware:
                    - handle_message

            messenger.bus.event:
                default_middleware: allow_no_handlers

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            # async: '%env(MESSENGER_TRANSPORT_DSN)%'
            # failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'
            events:
                dsn: '%env(RABBITMQ_DSN)%'
                retry_strategy:
                    delay: 2000
                    max_retries: 5
                    multiplier: 2
                    max_delay: 0

                options:
                    exchange:
                        type: topic
                        name: events
                    queues:
                        events:
                            binding_keys: ['#']

        routing:
            # Route your messages to the transports
            'App\Shared\Domain\Model\DomainEventInterface': events
